### ISSUE TITLE
Provide Streams for Paginated Endpoints

### ISSUE THREAD

**Issue by Nerixyz** [Emilgardis/twitch_api2#149]
When using paginated endpoints it's not always best to put it in a giant vector first and then return it like it's done currently. Often the items, for example followers, need to be processed in some way on their own (like storing old followers in a file). For this it's better to stream the items into the file (in this case).

So being able to do something like this would be nice:
```rust
async fn save_followers(file) -> AnyResult {
  let mut stream = client.stream_followers(...);

  while let Some(follower) = stream.try_next().await? {
    file.save_follower(&follower).await;
  }
  
  Ok(())
}
```

**Comment by Emilgardis** [comment]
I agree! There's nothing hindering you to do this in your own implementation currently, see https://github.com/Emilgardis/twitch_api2/blob/a12f3d9483a9c903dde9ce8cea07daa3453c3198/src/helix/mod.rs#L763.

Are you suggesting a stream type that does the get_next call for you on demand?

I dont have much knowledge of what alternatives there are for streams/generators, any suggestions?

**Comment by Nerixyz** [comment]
> There's nothing hindering you to do this in your own implementation currently, see

Yeah, I thought about making my own implementation. 


> Are you suggesting a stream type that does the get_next call for you on demand?

Yeah basically. I saw this for sql queries and I think this could be nice for this API.



> I dont have much knowledge of what alternatives there are for streams/generators, any suggestions?

I'm not that experienced with streams either, but there's [`async_stream`](https://docs.rs/async-stream) which makes it relatively easy through the `yield` statement. Though I'm not sure about the lifetimes within the stream.

**Comment by Emilgardis** [comment]
I've worked on a implementation I like for this in #159
