### ISSUE TITLE
`tag_ids` field in `Stream` after using `get_followed_streams()` can be null

### ISSUE THREAD

**Issue by dozn** [Emilgardis/twitch_api2#184]
Howdy!

It appears as if the Twitch API will _sometimes_ return `null` for the `tag_ids` field in `helix::Stream` after using `get_followed_streams()` for whatever reason.

It has occurred twice now within the span of a couple hours, although I unfortunately no longer have access to the first error message.

The second occurred with https://www.twitch.tv/xfsn_saber (I'm unsure if the specific stream actually matters), as upon running it once more ~thirty seconds afterwards, it ran without issue.

Something interesting to note, is that their stream also had `"viewer_count": 0`, but every other field was normal.

The relevant error message:
`Error { path: Path { segments: [Map { key: "data" }, Seq { index: 28 }, Map { key: "tag_ids" }] }, original: Error("invalid type: null, expected a sequence", line: 1, column: 14545) }, https://api.twitch.tv/helix/streams/followed?user_id=19957417, 200))`

Using v0.5.0.

Cheers!

**Comment by dozn** [comment]
There's apparently many more instances of people seeing the `tag_ids` as null from their API https://github.com/twitchdev/issues/issues/230

Doesn't seem like Twitch has fixed it just yet ;)

**Comment by Emilgardis** [comment]
fixed, but only in `0.6.0`

thank you!
