### ISSUE TITLE
Better exemple in the doc

### ISSUE THREAD

**Issue by Fr33maan** [Emilgardis/twitch_api2#233]
I'm unable to understand which features should be used in order to make the very first exemple in the doc working.
Do I need to reference the `twitch_oauth2` crate in `Cargo.toml` ? 

![Screenshot from 2021-12-12 23-35-12](https://user-images.githubusercontent.com/3482025/145720934-dfdf693d-c3c0-47be-9b0f-376da1687f32.png)
![Screenshot from 2021-12-12 23-35-02](https://user-images.githubusercontent.com/3482025/145720936-bca134a0-16dc-4d80-9115-426b4a46de1b.png)

**Comment by Fr33maan** [comment]
Apparently I do need to set twitch_oauth2 as a dependency, and to match the major version.

**Comment by Fr33maan** [comment]
And now the app refuses to compile.

**Comment by Emilgardis** [comment]
Im not sure i understand your issue, can you post the error message and not the squigly you get in vscode. 

Run

`cargo check`

**Comment by Fr33maan** [comment]
```
cargo check
    Checking twitch_oauth2 v0.5.2
error[E0599]: no function or associated item named `new` found for struct `surf::Client` in the current scope
  --> /home/freeman/.cargo/registry/src/github.com-1ecc6299db9ec823/twitch_oauth2-0.5.2/src/client.rs:37:40
   |
37 | ...   let client = surf::Client::new(); // If this fails to compile, please use feature `surf_client_curl` or specify surf with a client ...
   |                                  ^^^ function or associated item not found in `surf::Client`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `twitch_oauth2` due to previous error

```

**Comment by Fr33maan** [comment]
```
twitch_api2 = { version = "0.5.0", features = ["twitch_oauth2", "helix", "client", "surf_client"] }
twitch_oauth2 = "0.5.2"
```

**Comment by Fr33maan** [comment]
Imported `surf = "2.3.2"` and get better results. Since it's not explained anywhere in the exemple, hard to guess for a beginer

**Comment by Emilgardis** [comment]
There's a comment in the code it's referencing there.

```
If this fails to compile, please use feature `surf_client_curl` or specify surf with a client
```

You need to specify in Cargo.toml

```
[dependencies]
surf = "2.2"
```

or 
```
[dependencies]
twitch_api2 = { version = "0.5.0", features = ["twitch_oauth2", "helix", "client", "surf_client_curl"] }
```

(notice we're using `surf_client_curl` instead of just `surf_client`

**Comment by Emilgardis** [comment]
> Imported `surf = "2.3.2"` and get better results. Since it's not explained anywhere in the exemple, hard to guess for a beginer

There was no good way to explain it within the code, I guess I can make it clearer in the docs

**Comment by Fr33maan** [comment]
Yes, the beginer expects to read the exemple and know what to do.
You could explain that there is prerequisites like adding twitch_oauth2 as dependency, the list of necessary features to run the exemple.

**Comment by Fr33maan** [comment]
And now:
`the package `jeanbotiste` depends on `twitch_api2`, with features: `surf_client_curl` but `twitch_api2` does not have these features.`

**Comment by Emilgardis** [comment]
Oh sorry! `surf_client_curl` is a feature in twitch_oauth2!

**Comment by Fr33maan** [comment]
and twitch_oauth2 does not even have a features list on the doc

**Comment by Fr33maan** [comment]
Using the surf_client feature does not do the trick, I must import `surf = "2.2"`

**Comment by Emilgardis** [comment]
> and twitch_oauth2 does not even have a features list on the doc

most crates don't. see https://docs.rs/crate/twitch_oauth2/0.5.2/features

**Comment by Fr33maan** [comment]
But then another issue, how to create the `ClientId` and `ClientSecret` ?

**Comment by Fr33maan** [comment]
```
mismatched types
expected struct `ClientId`, found struct `String`
```

**Comment by Fr33maan** [comment]
Additionaly
```
no function or associated item named `new` found for struct `TwitchClient` in the current scope
function or associated item not found in `TwitchClient<'_, _>`
```

**Comment by Fr33maan** [comment]
Would you mind comming on my live to help me fix and be able to use the lib please ? 
https://www.twitch.tv/jean___baptiste

**Comment by Fr33maan** [comment]
Solution: use beta 0.6.0 for api and oauth
