### ISSUE TITLE
Implement all helix endpoints

### ISSUE THREAD

**Issue by Emilgardis** [Emilgardis/twitch_api2#3]
- [x] Moderation

    - [x] `POST https://api.twitch.tv/helix/moderation/enforcements/status` <a href="https://dev.twitch.tv/docs/api/reference#check-automod-status" class="">Check AutoMod Status</a>
        <sub>Determines whether a string message meets the channel’s AutoMod requirements.</sub> 
    - [x] `GET https://api.twitch.tv/helix/moderation/banned` <a href="https://dev.twitch.tv/docs/api/reference#get-banned-users" class="">Get Banned Users</a>
        <sub>Returns all banned and timed-out users in a channel.</sub> 
    - [x] `GET https://api.twitch.tv/helix/moderation/banned/events` <a href="https://dev.twitch.tv/docs/api/reference#get-banned-events" class="">Get Banned Events</a>
        <sub>Returns all user bans and un-bans in a channel.</sub> 
    - [x] `GET https://api.twitch.tv/helix/moderation/moderators` <a href="https://dev.twitch.tv/docs/api/reference#get-moderators" class="">Get Moderators</a>
        <sub>Returns all moderators in a channel.</sub> 
    - [x] `GET https://api.twitch.tv/helix/moderation/moderators/events` <a href="https://dev.twitch.tv/docs/api/reference#get-moderator-events" class="">Get Moderator Events</a>
        <sub>Returns a list of moderators or users added and removed as moderators from a channel.</sub> 

- [x] Channels

    - [x] `POST https://api.twitch.tv/helix/channels/commercial` <a href="https://dev.twitch.tv/docs/api/reference#start-commercial" class="">Start Commercial</a>
        <sub>Starts a commercial on a specified channel.</sub>
    - [x] `GET https://api.twitch.tv/helix/channels` <a href="https://dev.twitch.tv/docs/api/reference#get-channel-information" class="">Get Channel Information</a>
        <sub>Gets channel information for users.</sub>
    - [x] `PATCH https://api.twitch.tv/helix/channels` <a href="https://dev.twitch.tv/docs/api/reference#modify-channel-information" class="">Modify Channel Information</a>
        <sub>Modifies channel information for users.</sub> 

- [ ] Analytics
    - [ ] `GET https://api.twitch.tv/helix/analytics/extensions` <a href="https://dev.twitch.tv/docs/api/reference#get-extension-analytics" class="">Get Extension Analytics</a>
        <sub>Gets a URL that extension developers can use to download analytics reports (CSV files) for their extensions. The URL is valid for 5 minutes. For details about analytics and the fields returned, see the Insights Analytics Guide.</sub>
    - [ ] `GET https://api.twitch.tv/helix/analytics/games` <a href="https://dev.twitch.tv/docs/api/reference#get-game-analytics" class="">Get Game Analytics</a>
        <sub>Gets a URL that game developers can use to download analytics reports (CSV files) for their games. The URL is valid for 5 minutes. For detail about analytics and the fields returned, see the Insights Analytics guide.</sub> 

- [x] Bits

    - [x] `GET https://api.twitch.tv/helix/bits/cheermotes` <a href="https://dev.twitch.tv/docs/api/reference#get-cheermotes" class="">Get Cheermotes</a>
        <sub>Retrieves the list of available Cheermotes, animated emotes to which viewers can assign Bits, to cheer in chat. Cheermotes returned are available throughout Twitch, in all Bits-enabled channels.</sub> 
    - [x] `GET https://api.twitch.tv/helix/bits/leaderboard` <a href="https://dev.twitch.tv/docs/api/reference#get-bits-leaderboard" class="">Get Bits Leaderboard</a>
        <sub>Gets a ranked list of Bits leaderboard information for an authorized broadcaster.</sub> 

- [ ] Extensions

    - [ ] `GET https://api.twitch.tv/helix/extensions/transactions` <a href="https://dev.twitch.tv/docs/api/reference#get-extension-transactions" class="">Get Extension Transactions</a>
        <sub>Get Extension Transactions allows extension back end servers to fetch a list of transactions that have occurred for their extension across all of Twitch.</sub> 

- [ ] Clips

    - [ ] `POST https://api.twitch.tv/helix/clips` <a href="https://dev.twitch.tv/docs/api/reference#create-clip" class="">Create Clip</a>
        <sub>Creates a clip programmatically. This returns both an ID and an edit URL for the new clip.</sub> 
    - [x] `GET https://api.twitch.tv/helix/clips` <a href="https://dev.twitch.tv/docs/api/reference#get-clips" class="">Get Clips</a>
        <sub>Gets clip information by clip ID (one or more), broadcaster ID (one only), or game ID (one only).</sub> 

- Entitlements

    - [ ] `POST https://api.twitch.tv/helix/entitlements/upload` <a href="https://dev.twitch.tv/docs/api/reference#create-entitlement-grants-upload-url" class="">Create Entitlement Grants Upload URL</a>
        <sub>Creates a URL where you can upload a manifest file and notify users that they have an <em>entitlement</em>. Entitlements are digital items that users are entitled to use. Twitch entitlements are granted to users gratis or as part of a purchase on Twitch.</sub> 
    - [ ] `GET https://api.twitch.tv/helix/entitlements/codes` <a href="https://dev.twitch.tv/docs/api/reference#get-code-status" class="">Get Code Status</a>
        <sub>Codes are redeemable alphanumeric strings tied only to the bits product. This third-party API allows other parties to redeem codes on behalf of users. Third-party app and extension developers can use the API to provide rewards of bits from within their games.</sub> 
    - [ ] `POST https://api.twitch.tv/helix/entitlements/code` <a href="https://dev.twitch.tv/docs/api/reference#redeem-code" class="">Redeem Code</a>
        <sub>Codes are redeemable alphanumeric strings tied only to the bits product. This third-party API allows other parties to redeem codes on behalf of users. Third-party app and extension developers can use the API to provide rewards of bits from within their games.</sub> 

- [x] Games

    - [x] `GET https://api.twitch.tv/helix/games/top` <a href="https://dev.twitch.tv/docs/api/reference#get-top-games" class="">Get Top Games</a>
        <sub>Gets games sorted by number of current viewers on Twitch, most popular first.</sub> 
    - [x] `GET https://api.twitch.tv/helix/games` <a href="https://dev.twitch.tv/docs/api/reference#get-games" class="">Get Games</a>
        <sub>Gets game information by game ID or name.</sub> 

- [x] Search

    - [x] `GET https://api.twitch.tv/helix/search/categories` <a href="https://dev.twitch.tv/docs/api/reference#search-categories" class="">Search Categories</a>
        <sub>Returns a list of games or categories that match the query via name either entirely or partially.</sub> 
    - [x] `GET helix/search/channels` <a href="https://dev.twitch.tv/docs/api/reference#search-channels" class="">Search Channels</a>
        <sub>Returns a list of channels (users who have streamed within the past 6 months) that match the query via channel name or description either entirely or partially. Results include both live and offline channels. Online channels will have additional metadata (<em>e.g.</em> `started_at`, `tag_ids`). See sample response for distinction.</sub> 

- [ ] Streams

    - [ ] `https://api.twitch.tv/helix/streams/key` <a href="https://dev.twitch.tv/docs/api/reference#get-stream-key" class="">Get Stream Key</a>
        <sub>Gets the channel stream key for a user.</sub> 
    - [x] `GET https://api.twitch.tv/helix/streams` <a href="https://dev.twitch.tv/docs/api/reference#get-streams" class="">Get Streams</a>
        <sub>Gets information about active streams. Streams are returned sorted by number of current viewers, in descending order. Across multiple pages of results, there may be duplicate or missing streams, as viewers join and leave streams.</sub> 
    - [ ] `POST https://api.twitch.tv/helix/streams/markers` <a href="https://dev.twitch.tv/docs/api/reference#create-stream-marker" class="">Create Stream Marker</a>
        <sub>Creates a <em>marker</em> in the stream of a user specified by a user ID. A marker is an arbitrary point in a stream that the broadcaster wants to mark; e.g., to easily return to later. The marker is created at the current timestamp in the live broadcast when the request is processed. Markers can be created by the stream owner or editors. The user creating the marker is identified by a Bearer token.</sub> 
    - [ ] `GET https://api.twitch.tv/helix/streams/markers` <a href="https://dev.twitch.tv/docs/api/reference#get-stream-markers" class="">Get Stream Markers</a>
        <sub>Gets a list of <em>markers</em> for either a specified user’s most recent stream or a specified VOD/video (stream), ordered by recency. A marker is an arbitrary point in a stream that the broadcaster wants to mark; e.g., to easily return to later. The only markers returned are those created by the user identified by the Bearer token.</sub> 
    - [x] `GET https://api.twitch.tv/helix/streams/tags` <a href="https://dev.twitch.tv/docs/api/reference#get-stream-tags" class="">Get Stream Tags</a>
        <sub>Gets the list of tags for a specified stream (channel).<br>The response has a JSON payload with a `data` field containing an array of tag elements.</sub> 
    - [ ] `PUT https://api.twitch.tv/helix/streams/tags` <a href="https://dev.twitch.tv/docs/api/reference#replace-stream-tags" class="">Replace Stream Tags</a>
        <sub>Applies specified tags to a specified stream, overwriting any existing tags applied to that stream. If no tags are specified, all tags previously applied to the stream are removed. Automated tags are not affected by this operation.</sub> 

- [x] Subscriptions

    - [x] `GET https://api.twitch.tv/helix/subscriptions` <a href="https://dev.twitch.tv/docs/api/reference#get-broadcaster-subscriptions" class="">Get Broadcaster Subscriptions</a>
        <sub>Gets all of a broadcaster’s subscriptions.</sub>

- [x] Tags
    - [x] `GET https://api.twitch.tv/helix/tags/streams` <a href="https://dev.twitch.tv/docs/api/reference#get-all-stream-tags" class="">Get All Stream Tags</a>
        <sub>Gets the list of all stream tags defined by Twitch, optionally filtered by tag ID(s).</sub> 

- [ ] Users

    - [x] `POST https://api.twitch.tv/helix/users/follows`&nbsp; <a href="https://dev.twitch.tv/docs/api/reference#create-user-follows" class="">Create User Follows</a>
        <sub>Adds a specified user to the followers of a specified channel.</sub> 
    - [x] `DELETE https://api.twitch.tv/helix/users/follows` <a href="https://dev.twitch.tv/docs/api/reference#delete-user-follows" class="">Delete User Follows</a>
        <sub>Deletes a specified user from the followers of a specified channel.</sub> 
    - [x] `GET https://api.twitch.tv/helix/users` <a href="https://dev.twitch.tv/docs/api/reference#get-users" class="">Get Users</a>
        <sub>Gets information about one or more specified Twitch users. Users are identified by optional user IDs and/or login name. If neither a user ID nor a login name is specified, the user is looked up by Bearer token.</sub> 
    - [x] `GET https://api.twitch.tv/helix/users/follows` <a href="https://dev.twitch.tv/docs/api/reference#get-users-follows" class="">Get Users Follows</a>
        <sub>Gets information on follow relationships between two Twitch users. Information returned is sorted in order, most recent follow first. This can return information like “who is qotrok following,” “who is following qotrok,” or “is user X following user Y.”</sub> 
    - [x] `PUT https://api.twitch.tv/helix/users` <a href="https://dev.twitch.tv/docs/api/reference#update-user" class="">Update User</a>
        <sub>Updates the description of a user specified by a Bearer token.</sub> 
    - [ ] `GET https://api.twitch.tv/helix/users/extensions/list` <a href="https://dev.twitch.tv/docs/api/reference#get-user-extensions" class="">Get User Extensions</a>
        <sub>Gets a list of all extensions (both active and inactive) for a specified user, identified by a Bearer token.</sub> 
    - [ ] `GET https://api.twitch.tv/helix/users/extensions` <a href="https://dev.twitch.tv/docs/api/reference#get-user-active-extensions" class="">Get User Active Extensions</a>
        <sub>Gets information about active extensions installed by a specified user, identified by a user ID or Bearer token.</sub> 
    - [ ] `PUT https://api.twitch.tv/helix/users/extensions` <a href="https://dev.twitch.tv/docs/api/reference#update-user-extensions" class="">Update User Extensions</a>
        <sub>Updates the activation state, extension ID, and/or version number of installed extensions for a specified user, identified by a Bearer token. If you try to activate a given extension under multiple extension types, the last write wins (and there is no guarantee of write order)</sub> 

- [x] Videos

    - [x] `GET https://api.twitch.tv/helix/videos` <a href="https://dev.twitch.tv/docs/api/reference#get-videos" class="">Get Videos</a>
        <sub>Gets video information by video ID (one or more), user ID (one only), or game ID (one only).</sub>

- [ ] Webhooks

    - [ ] `GET https://api.twitch.tv/helix/webhooks/subscriptions` <a href="https://dev.twitch.tv/docs/api/reference#get-webhook-subscriptions" class="">Get Webhook Subscriptions</a>
        <sub>Gets the Webhook subscriptions of a user identified by a Bearer token, in order of expiration.</sub> 
        
- [ ] Hypetrain

    - [ ] `GET https://api.twitch.tv/helix/hypetrain/events` <a href="https://dev.twitch.tv/docs/api/reference#get-hype-train-events" class="active-highlight">Get Hype Train Events</a>
         <sub>Gets the information of the most recent Hype Train of the given channel ID. When there is currently an active Hype Train, it returns information about that Hype Train. When there is currently no active Hype Train, it returns information about the most recent Hype Train.&nbsp; After 5 days, if no Hype Train has been active, the endpoint will return an empty response.</sub>

**Comment by Dinnerbone** [comment]
FYI the rewards/points endpoints are missing from this list. I've started to implement some that I need but not comprehensively, if you'd want a PR for that.

**Comment by Emilgardis** [comment]
> FYI the rewards/points endpoints are missing from this list. I've started to implement some that I need but not comprehensively, if you'd want a PR for that.

Great! That's new and certainly makes me happy to see.
PRs are welcome :)

**Comment by Emilgardis** [comment]
closing this issue, the code itself should suffice for tracking, and a [xtask ](https://github.com/Emilgardis/twitch_api2/pull/71) program can solve outdated wiki.
