### ISSUE TITLE
Tokio v1 support

### ISSUE THREAD

**Issue by DanielVoogsgerd** [Emilgardis/twitch_api2#65]
Attempting to run this library with the version 1 version of Tokio yields the following error:

```
thread 'main' panicked at 'not currently running on the Tokio runtime.', {..}/tokio-0.2.24/src/runtime/handle.rs:118:28
```

Considering tokio released its v1 maybe it's time to upgrade the version of tokio as well.

**Comment by Emilgardis** [comment]
This is in the pipeline, blocked on upgrading oauth2 to new 4.0.0-alpha.3 version.

a new alpha version of twitch_oauth2 and twitch_api2 should be out soon :) I'll make a real release with oauth2 is not in rc anymore!

**Comment by DanielVoogsgerd** [comment]
Ah cool! Thanks for the info

**Comment by Emilgardis** [comment]
closing this issue, see https://github.com/Emilgardis/twitch_api2/issues/62 for more info
