### ISSUE TITLE
Total field should be a root field instead of being a UsersFollow field

### ISSUE THREAD

**Issue by novelhawk** [Emilgardis/twitch_api2#95]
https://github.com/Emilgardis/twitch_api2/blob/0674ab042e601af55cf149990f2b461652c6db00/src/helix/users/get_users_follows.rs#L79-L85

The struct UsersFollow currently contains `total` which should be in the Response root json object as of the example in [twitch docs](https://dev.twitch.tv/docs/api/reference#get-users-follows):

```json
{
   "total": 12345, // <-- The actual field is here
   "data":
   [
      {
         "from_id": "171003792",
         "from_login": "iiisutha067iii",
         "from_name": "IIIsutha067III",
         "to_id": "23161357",
         "to_name": "LIRIK",
         "followed_at": "2017-08-22T22:55:24Z"
         // <-- Right now the library looks for it here
      },
      {
         "from_id": "113627897",
         "from_login": "birdman616",
         "from_name": "Birdman616",
         "to_id": "23161357",
         "to_name": "LIRIK",
         "followed_at": "2017-08-22T22:55:04Z"
         // <-- And also here
      },
      // ...
   ],
   "pagination":{
     "cursor": "eyJiIjpudWxsLCJhIjoiMTUwMzQ0MTc3NjQyNDQyMjAwMCJ9"
   }
}
```

Get Webhook Subscriptions also does the same thing but is currently ignored in the library. There might be other examples.

**Comment by Emilgardis** [comment]
Thanks for the report!

Totally missed this, it's a common pattern and it's already fixed for Get Bits Leaderboard

https://github.com/Emilgardis/twitch_api2/blob/0674ab042e601af55cf149990f2b461652c6db00/src/helix/bits/get_bits_leaderboard.rs#L128-L176


I'll see if there's an easy way to make this work without much duplication, perhaps like I discussed in https://github.com/Emilgardis/twitch_api2/pull/93#discussion_r604410946
